### ISSUE TITLE
Portals - Quest's

### ISSUE THREAD

**Issue by rashidragon** [aatxe/Orpheus#1]
1-some portals are not working like the one in NLC subway station, henesys pack the portal to bowman job instructor

2- some quest works fine but others just wont finish even when you get every thing that is REQ you just click on OK but nothing happens 

3-monsters keep dropping from there stage

**Comment by aatxe** [comment]
What quests don't work? It's likely an issue with the scripts for them, and each are individual.

**Comment by aatxe** [comment]
No follow up on this issue, going to call it fixed. (The third one never happened, so he may have just had some weird setup)
