### ISSUE TITLE
Quest issue

### ISSUE THREAD

**Issue by Shimuriel** [aatxe/Orpheus#12]
At level 15 you get an automatic quest from the mapleadmin that pops up, it is called "A Mysterious Small Egg" and it places a small egg in your bag. You take this egg to Mar the Pet fairy in Ellinia and she turns it into a "Snail" pet. The pet is supposed to die after 5 hours but the quest timer does not change. Normally it would be fine but the snail is supposed to go away I think because it keeps getting summoned on its own. 

Is there a command to remove an item from inventory? When using the !search I could not find the code for this snail.

**Comment by aatxe** [comment]
Confirmed as an issue. Not sure if I'm going to do anything about it.

**Comment by Shimuriel** [comment]
Yea its easily avoided, toss out the egg and forget about it lol.

**Comment by Shimuriel** [comment]
I didn't think about this but you might take the egg out so people never get the snail.

**Comment by aatxe** [comment]
Yep, easy to fix: just don't do the quest.
