### ISSUE TITLE
Map errors

### ISSUE THREAD

**Issue by Shimuriel** [aatxe/Orpheus#16]
There is a map in the forest near ellinia called the "Top of The Tree That Grew" (id - 101010103). When you jump off you hit the bottom and get stuck. I assume it supposed to teleport you at the bottom but its broken.

**Comment by jerryguo41** [comment]
Works on testing server. Try again probably just happen that one time due to some weird coincidences.

**Comment by aatxe** [comment]
Confirmed working. Might've just had a bad connection or something.

**Comment by Shimuriel** [comment]
Yea mine is still broken. I can't help but reflect back to MySQL Workbench crashing and me having to use MySQL Browser to execute the SQL's. Even though it worked without errors it still worries me that maybe something didn't get read correctly by Workbench. Do you both use the same SQL browser?

Is it even possible that one program could read something differently or have a "language" discrepancy?

**Comment by aatxe** [comment]
We're both on the same server (my testing server). I used Navicat for MySQL.

However, it honestly shouldn't make a difference as MySQL is a standardized language.

**Comment by Shimuriel** [comment]
You need someone else that's not on your server testing stufffs.

**Comment by aatxe** [comment]
Have you tried replicating this issue again?
