### ISSUE TITLE
infinite scroll bug?

### ISSUE THREAD

**Issue by Shimuriel** [aatxe/Orpheus#17]
A player of mine tells me that she bought some scrolls (scroll for wand for magic att, scroll for bottom for def, etc)
from the scroll vender near Ellinia and started scrolling her gear. The first couple of scrolls took away slots from the gear then it became infinite (no longer took slots away).

**Comment by aatxe** [comment]
Cannot replicate issue. Sorry.
The only way this can happen is if you're a GM.
GMs don't use scrolls.
