### ISSUE TITLE
White tiger stacking

### ISSUE THREAD

**Issue by Shimuriel** [aatxe/Orpheus#18]
I have three white tigers in my bag and when I try to move them they stack and disappear, sometimes causes a crash. They are all named btw.

**Comment by Shimuriel** [comment]
He also doesn't seem to want to eat the white tiger nexon food. Is there anywhere else (aside from the item/pet script) that pet scripting is located? I'd like to just look at his script and compare it to other pets.

**Comment by aatxe** [comment]
I could not replicate this issue. However, attempting to stack the same pets (or dragging and dropping one onto another) does seem to cause a crash. Or at least, it did with White Tigers.
