### ISSUE TITLE
Missing maps

### ISSUE THREAD

**Issue by Shimuriel** [aatxe/Orpheus#19]
The "Cave of Trials" maps that links "The Passage" (211041900) to "The Door to Zakum" (211042300) is missing. Is this done for a reason maybe? Two maps are missing, "The case of Trials I" (211042000) and "The Cave of Trials III" (211042200).

**Comment by Shimuriel** [comment]
Just noticed the maps are there but I can't use !map to go to them and the teleporters that link the connecting maps are down.

**Comment by aatxe** [comment]
Using `@cody` you'll be able to go to the boss map to fight Zakum. I'm unsure as to why the portals don't work. However, there ARE scripts for the portals. So, you could skip it. According to MapleTip, Cave of Trials isn't a map. So, I don't know what to tell you.

**Comment by Shimuriel** [comment]
No biggies I'm just going through stuff as I get to it and reporting weirdness. But yea I can see adding a warp npc to zakum's chamber also (to be more GMS like) for players who like to discover things for themselves heh.
