### ISSUE TITLE
GM Commands

### ISSUE THREAD

**Issue by rashidragon** [aatxe/Orpheus#2]
how about adding player commands with gm command when the user is gm instead of only gm commands

**Comment by aatxe** [comment]
Yeah, this was the first bug that I experienced in my tests. I've been a bit busy but I should get back to updating everything soon. It's an issue with the system I put in place for command overriding. For one reason or another, it doesn't seem to like falling back on lower ranked commands, so you can only use commands for your rank. I have an idea for a fix though.

**Comment by aatxe** [comment]
Should be fixed as of commit a402a02836.
Confirmation needed.

**Comment by aatxe** [comment]
Fix in commit a402a02 failed, working on some more.

**Comment by aatxe** [comment]
Confirmed working as of commit bfebdf1519. :)
