### ISSUE TITLE
Can't Get Past Character Selection

### ISSUE THREAD

**Issue by eNGene** [aatxe/Orpheus#25]
I'm sorry if no one's having issues with this one but me. But I am sort of new to this so if you could help out that would be very much appreciated

I can't seemed to get past the character selection, even after changing the IP on the conststant.

**Comment by aatxe** [comment]
Did you recompile after changing the IP?

**Comment by aatxe** [comment]
Nonissue, and no response. Closing this.
If you need help, contact me via email or PM or something.
