### ISSUE TITLE
Python Scripting

### ISSUE THREAD

**Issue by aatxe** [aatxe/Orpheus#26]
Convert everything over to Python for scripting.
Keep an option to use JavaScript still.
Fallback to JavaScript for unimplemented scripts, and vice versa.
Have a handler that manages between the two based on settings.

It'll be some awesome shit.

**Comment by elwl** [comment]
cool beans yo ^ㅂ^

**Comment by aatxe** [comment]
This project has been discontinued for a while. Thus, I'm closing the issue.
