### ISSUE TITLE
Creating a character

### ISSUE THREAD

**Issue by eriicz** [aatxe/Orpheus#28]
How would I go about fixing my setup problem then?

**Comment by aatxe** [comment]
You can comment on closed issues, but anyway, I don't know what exactly is the cause of the problem. You'd have to give me more information.

**Comment by eriicz** [comment]
Oh sorry
Well I get an error:
java.lang.Nullpointerexception
at client.Maplecharacter.savetodbmaplecharacter.java:3606
at net.server.handlers.login.createcharhandler.handlepacketcreatecharhandler.java:97
at net.mapleserverhandler.messagerecievedmapleserverhandler.java:128
at org.apache.mina.core.filterchain.defaultIofilterchain$tailfilter etcetc
Whenever I try to create a character.

**Comment by aatxe** [comment]
Be sure to disable MapleStocks in ServerConstants, if you're not using it.
(You shouldn't, because it's broken, and still needs work).

If this doesn't fix it, download the stable build.
