### ISSUE TITLE
Remove GM Server

### ISSUE THREAD

**Issue by aatxe** [aatxe/Orpheus#3]
The built-in GM Server seems pointless, and like it causes more problems than its worth. The functionality is abstract, and it's difficult to understand. I think it would be best if I removed it at some point.

**Comment by aatxe** [comment]
I made it actually toggle-able using the property in the config file.

**Comment by Shimuriel** [comment]
Do you need a GM server to make a GM account? (newb question probably)

**Comment by aatxe** [comment]
No, you shouldn't use it fi you don't know what it is.
