### ISSUE TITLE
Character Deletion NPC

### ISSUE THREAD

**Issue by aatxe** [aatxe/Orpheus#4]
I should probably make an NPC that allows you to delete characters on your account.
The idea is to use the pin field, or possibly the pic field, in combination with the NPC.
This way, you still get all of the security that a pin/pic has to offer to prevent character deletion, whilst not having to enter you pin just to login. It's certain to be an optional feature though, definitely with settings in ServerConstants to disable it.

**Comment by aatxe** [comment]
Implemented as of commit e05ba1d7cb3377487cedaf16848134d9085fb9e2

**Comment by Shimuriel** [comment]
I read for mooplestory I think, that the maple administrator in FM was the character deletion NPC, if so she doesn't seem to work atm.
