### ISSUE TITLE
Kerning subway and Ellinia/Orbis ticket NPC issue.

### ISSUE THREAD

**Issue by Shimuriel** [aatxe/Orpheus#7]
In ellinia/orbis the ticket seller will not sell you tickets so the boat is inaccessible. In kerning subway the ticket seller sells the ticket but the thing you click to enter the subway train doesn't port you.

**Comment by aatxe** [comment]
I'll investigate this.

**Comment by aatxe** [comment]
You're able to get on boats without using tickets. I'll check out the subway, too.

**Comment by Shimuriel** [comment]
I am having irreconcilable issues apparently because I cannot get on the boat without a ticket. I placed the ticket in my inventory with !item 4031045 1 and I could board the boat.

**Comment by aatxe** [comment]
I only took the boat from Orbis to Ellinia. I probably should've checked more.

**Comment by Shimuriel** [comment]
Ok my game is installed correctly. Cherry on Ellinia docks won't let me on the boat (I assume I just talk to Cherry to board?).

**Comment by Shimuriel** [comment]
The boat from Ellinia to Nautilous is not working either (unless you need special access/quest access).

**Comment by jerryguo41** [comment]
The ticket reader for the NLC - > Kerning City subway does not work. On the other hand going from Kerning City -> NLC works by clicking on the ticket booth behind your hot-key area. Also the portal going to the mall does not work.

**Comment by Shimuriel** [comment]
Ho'kay. Here is the scoup, someone else try this and confirm it please. If you have no ticket for the subway the reader does NOT let you on right? Well I went to kerning city subway and bought a ticket... nothing. I went to NLC subway and tried to get on the train without a ticket... it worked. So I checked and dropped the kerning ticket I had in my bag on the ground. NLC reader wouldn't let me on. So, I surmise the issue is this...

You have the codes for the tickets backwards. Switch the kerning ticket code that the ticket seller sells you and the NLC ticket code and it should be fixed. Shazam! If I could find the codes I would switch it myself. EDIT: I found one reader but there should be two. I am going to leave this to the pro's. The ticket readers are reversed though for sure.

_(cough)_ Orbis boats are still broken. >.< Lol.

Note: I am starting to wonder, since in my version of MS (client) I think the maple admin is a quest NPC which renders her toon deletion script null. Could this be a issue with the boats? I need to get a link to your v83 download to make certain were on the same page. You may want to post a link to YOUR v83 that you use for everyone to download if this is the case (there are to many v83's out there and I have no clue if there all the same).

EDIT: Ok it is NOT the ticket seller that needs changed it is the Ticket Reader that needs to have the codes switched. I found one ticket reader id 1052007 but there are two of them? Unless they share a script.

**Comment by Shimuriel** [comment]
Ticket <to> kerning city (regular) - sold at NLC subway (id 4031713)
Ticket <to> NLC (regular) - sold at kerning subway (id 4031711)

If you look at the dialogue when you click the reader at NLC you see the numbers are backwards at the two stations.

**Comment by Shimuriel** [comment]
I changed the ticket number from 4031713 to 4031711 in script NPC file 1052007 (kerning ticket reader) and it fixed the ride TO NLC. I'll check the ride back now.

I changed the ticket numder from 4031711 to 4031713 in script NPC file 9201068 (NLC ticket reader) and it fixed the ride to NLC. Subway works now bro. I'll email them to you in case your feeling lazy.

Boats are beyond me atm. =)

**Comment by jerryguo41** [comment]
v.83 download: http://cl.ly/2y3C0H1X3t290e1T1M3b

**Comment by Shimuriel** [comment]
Ok i sent you another (more updated) copy of each ticket reader file, it seems in NPC script 9201068 there was a missing "t" that made the text glitch. (text += "\r\n#L0##t4031713#";) I put it in there with the changed number code for the tickets. Trust me (famous last words heh). So there in the second email. Script changes are a terrible thing when your OCD.

**Comment by aatxe** [comment]
That cloud app link is just a link through to Nexon's official v83 setup, just so you know.

**Comment by Shimuriel** [comment]
Ok i got your boat fix mang. Its in the mail.

**Comment by Shimuriel** [comment]
Shazam!
