### ISSUE TITLE
Items placed on hotkeys (keysettings) drop after logging

### ISSUE THREAD

**Issue by Shimuriel** [aatxe/Orpheus#8]
Items (not all but potions) placed on the keysettings and on your pet menu in equipment (for autopotting) drop off after logging completely out of the game (closing client). I have also noticed increased zone crashing (to login) when items are hotbarred. Notice that certain key settings reset to default when moved.

**Comment by aatxe** [comment]
This may just be an issue with your server not saving properly for some reason.
Does the issue still occur if you use the save command before logging off?

**Comment by Shimuriel** [comment]
This issue is seemingly related to the pet bug I mentioned. Having the nexon pet (bunny in my case with auto HP and MP equiped, it is also named) summoned when I leave henesys through the east portal and enter Ellinia from the bottom left portal (not sure if there are other portals) causes a crash to login. After the crash items bound to certain keys on the keyconfig reset. If you drop the pet (un-summon it) no crash occurs and thus no key reset. I have even experienced a crash from the cash shop on exiting while the pet was summoned. So in other words its the pets not the hotkeys causing the issue. 

And to answer your question directly, no it does not. Only occurs on crash from pet bug.

I did notice another small bug thats hardly worth mentioning here but I will for the sake of completion. When naming my pet with the nexon name tag it doesn't update the name right away nor does it use the nexon item on the first renaming. I have to log out and back in for the name to change and the item remains in my bag. Once named the pet can be named again with no problem and no logging out.
